[scratchpad] Add some perf counters to scratchpad
libra/libra pull request #6205
Opened 2020-09-24 23:18 UTC by andll

Adding counters for sparse merkle tree update and leaf node hashing to analyze it's performance

This is to triage performance regression that appears when gas price is set to non-zero value

2020-09-24 23:20 UTC, lightmark approved these changes
lgtm. Are you going to remove it once the triage is done?

2020-09-24 23:20 UTC, andll commented
I actually want to keep them, since they might come useful later. What are you thoughts on that?

2020-09-24 23:22 UTC, libra-action commented
**LSR dependency change summary**:
```
target packages:
  A libra-metrics 0.1.0 (workspace, path 'common/metrics')
    * features: [none]
  A futures 0.3.5 (direct third-party, crates.io)
    * features: alloc, async-await, default, executor, futures-executor, std
  A hyper 0.13.7 (direct third-party, crates.io)
    * features: default, runtime, socket2, stream, tcp
  A tokio 0.2.22 (direct third-party, crates.io)
    * features: blocking, default, fnv, futures-core, io-driver, io-util, iovec, lazy_static, memchr, mio, rt-core, slab, stream, sync, tcp, time
  A futures-channel 0.3.5 (transitive third-party, crates.io)
    * features: alloc, default, futures-sink, sink, std
  A futures-core 0.3.5 (transitive third-party, crates.io)
    * features: alloc, default, std
  A futures-executor 0.3.5 (transitive third-party, crates.io)
    * features: std
  A futures-io 0.3.5 (transitive third-party, crates.io)
    * features: std
  A futures-sink 0.3.5 (transitive third-party, crates.io)
    * features: alloc, default, std
  A futures-task 0.3.5 (transitive third-party, crates.io)
    * features: alloc, once_cell, std
  A futures-util 0.3.5 (transitive third-party, crates.io)
    * features: alloc, async-await, async-await-macro, channel, futures-channel, futures-io, futures-macro, futures-sink, io, memchr, proc-macro-hack, proc-macro-nested, sink, slab, std
  A h2 0.2.6 (transitive third-party, crates.io)
    * features: [none]
  A hashbrown 0.8.2 (transitive third-party, crates.io)
    * features: raw
  A http 0.2.1 (transitive third-party, crates.io)
    * features: [none]
  A http-body 0.3.1 (transitive third-party, crates.io)
    * features: [none]
  A httparse 1.3.4 (transitive third-party, crates.io)
    * features: default, std
  A indexmap 1.5.1 (transitive third-party, crates.io)
    * features: [none]
  A iovec 0.1.4 (transitive third-party, crates.io)
    * features: [none]
  A mio 0.6.22 (transitive third-party, crates.io)
    * features: default, with-deprecated
  A net2 0.2.34 (transitive third-party, crates.io)
    * features: default, duration
  A pin-project 0.4.23 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-lite 0.1.7 (transitive third-party, crates.io)
    * features: [none]
  A pin-utils 0.1.0 (transitive third-party, crates.io)
    * features: [none]
  A proc-macro-nested 0.1.6 (transitive third-party, crates.io)
    * features: [none]
  A slab 0.4.2 (transitive third-party, crates.io)
    * features: [none]
  A socket2 0.3.12 (transitive third-party, crates.io)
    * features: [none]
  A tokio-util 0.3.1 (transitive third-party, crates.io)
    * features: codec, default
  A tower-service 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  A tracing 0.1.19 (transitive third-party, crates.io)
    * features: log, std
  A tracing-core 0.1.15 (transitive third-party, crates.io)
    * features: lazy_static, std
  A try-lock 0.2.3 (transitive third-party, crates.io)
    * features: [none]
  A want 0.3.0 (transitive third-party, crates.io)
    * features: [none]
  M itoa 0.4.6 (transitive third-party, crates.io)
    * added features: default, std
    * (unchanged features: [none])

host packages:
  A futures-macro 0.3.5 (transitive third-party, crates.io)
    * features: [none]
  A pin-project-internal 0.4.23 (transitive third-party, crates.io)
    * features: [none]
  A proc-macro-hack 0.5.18 (transitive third-party, crates.io)
    * features: [none]
  M syn 1.0.41 (direct third-party, crates.io)
    * added features: visit-mut
    * (unchanged features: clone-impls, default, derive, extra-traits, full, parsing, printing, proc-macro, quote, visit)
```
<!-- metadata: {"tag":"lsr-summary"} -->

2020-09-24 23:22 UTC, lightmark commented
I feel it is better to have all-or-none instrumenting. what's your thoughts, @wqfish ?

2020-09-24 23:26 UTC, andll commented
What is all-or-none instrumenting? My thought is that it is always good perf counters as long as they are cheap(and those ones are). Some visibility >> no visibility.
As we need to track more parts, we can add more counters.

Otherwise every time we have perf problems we would have to add same counters to temporary PRs

2020-09-25 00:35 UTC, davidiw requested changes
this PR adds a lot of dependencies to LSR, please adjust

2020-09-25 00:35 UTC, davidiw commented on storage/scratchpad/src/sparse_merkle/counters.rs
> +use libra_metrics::{register_histogram, Histogram};
looks like somehow this is being pulled into LSR, you can import this through libra_secure_push_metrics without impacting it

2020-09-25 00:54 UTC, andll commented
Is it going to work inside libra node if I import through secure push metric?

Sent from my iPhone

On Sep 24, 2020, at 5:35 PM, David Isaac Wolinsky <notifications@github.com> wrote:

﻿

@davidiw requested changes on this pull request.

this PR adds a lot of dependencies to LSR, please adjust

________________________________

In storage/scratchpad/src/sparse_merkle/counters.rs<https://github.com/libra/libra/pull/6205#discussion_r494683141>:

> @@ -0,0 +1,26 @@
+use libra_metrics::{register_histogram, Histogram};


looks like somehow this is being pulled into LSR, you can import this through libra_secure_push_metrics without impacting it

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/libra/libra/pull/6205#pullrequestreview-496036573>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AAWVVQOJVCDP2F37MFCRRPDSHPQU3ANCNFSM4RY36N3A>.

2020-09-25 01:02 UTC, davidiw commented
I need to double check, because now I'm wondering if my metrics will be properly picked up. We may need to separate out our counters from our metrics service.... Since the way lazy initialization works is it is based upon the compiled library. If we compile two prometheus, it will go to the one we reference. If pull metrics has its own statics, it won't pick up the statics for push.

2020-09-25 01:03 UTC, davidiw commented
cc: @metajack / @bmwill on metrics and statics

2020-09-25 01:10 UTC, davidiw commented
looks like we need to build a core-metrics crate and have a metrics-server or pull-metrics crate :/

2020-09-25 01:12 UTC, bmwill commented
Yeah we technically need to do the same with our logging stuff

2020-09-25 03:03 UTC, davidiw commented
https://github.com/libra/libra/pull/6210 this will enable universal logging

2020-09-25 03:04 UTC, davidiw commented
> I feel it is better to have all-or-none instrumenting. what's your thoughts, @wqfish ?

@andll I suspect he is saying either have this everywhere in storage or no where, this is just a single point of interest across the many potential...

2020-10-09 20:57 UTC, davidiw commented
Feel free to re-open if you'd like to resume.

2020-10-09 20:57 UTC, closed without merging