Enabling Int Overflow Protection for Release Builds
libra/libra pull request #6325
Opened 2020-10-01 22:33 UTC by mickayz

## Motivation

The Rust compiler does not enable overflow protection for release builds by default.  Enabling this protection will add a check that validates whether an arithmetic operation will overflow the resulting value and panic if so. There is a tradeoff here since panics should generally be avoided, but given that arithmetic errors in Libra could silently lead to severe vulnerabilities including inconsistencies in account balances, consensus errors, liveliness errors, and other unknown unknowns, this tradeoff seems like the right one to make.  There should be no use case where allowing int overflows to occur is necessary.

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

## Test Plan

CI tests

2020-10-01 22:43 UTC, davidiw commented
/canary

2020-10-01 22:51 UTC, bmwill commented
IIRC these checks are enabled by default in debug builds but disabled in release builds. Given overflow can cause some interesting corner cases if not handled properly I agree that we should have these checks enabled for our production builds.

2020-10-01 23:19 UTC, bors-libra commented
:sunny: Canary successful

2020-10-02 00:45 UTC, dariorussi commented
fwiw I believe all interesting places in the VM where using `add_checked` and similar. Of course this PR is more than just the VM so it's fine particularly given it does not seem to have any perf impact.
This was just a fyi

2020-10-02 01:07 UTC, davidiw commented
Actually there seems to be a 5% perf regression :O
Probably worth it though

2020-10-07 01:11 UTC, davidiw commented
Would anyone be up to starting a 1 week or 2 week long longevity test on this immediately? If not, I vote we postpone until next year.

2020-10-07 15:51 UTC, bmwill commented
> Would anyone be up to starting a 1 week or 2 week long longevity test on this immediately? If not, I vote we postpone until next year.

That's actually a really good idea, given we haven't had any long running tests with this enabled we should ideally make sure its battle tested until decide to flip it on for everything

2020-10-08 20:14 UTC, davidiw requested changes
Let's postpone and get this into its own longevity test running on a dedicated testnet with lots of cluster testing going on.

2020-10-09 21:01 UTC, davidiw commented
Feel free to re-open if you'd like to resume.

2020-10-09 21:01 UTC, closed without merging