[Vault] Automatically trim old/stale keys after key rotations.
libra/libra pull request #6354
Opened 2020-10-03 00:15 UTC by JoshLind

## Motivation

This PR updates the vault client to automatically trim the number of keys held in vault after each key rotation. This prevents vault from collecting old/stale keys that should be discarded (and might otherwise be cause for security vulnerabilities, e.g., key gathering attacks). To achieve this, the PR offers two commits:

1. First, we update the vault client to automatically trim the key versions held in storage after each key rotation. The maximum number of keys is hard-coded at 4 (a rough guesstimate: a higher number might be problematic, a lower number might be too strict and make failure recovery more difficult).
2. Second, we add a unit test to verify this functionality.

Note that before keys can be trimmed in vault, the minimum encryption/decryption versions must be updated, otherwise the call will fail. The vault API for trimming keys can be found here: https://www.vaultproject.io/api-docs/secret/transit

### Have you read the [Contributing Guidelines on pull requests](https://github.com/libra/libra/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

## Test Plan

All tests pass locally, including the newly added one.

## Related PRs

None.

2020-10-03 00:31 UTC, davidiw requested changes
Awesome first stab and glad to see we have all the pieces. The problem with this approach is that you assume that the retrieve of a public key should have write abilities on that key, that's dangerous. I would equate rotate privileges as ability to delete / trim. Let's unify it at that layer.

2020-10-03 00:48 UTC, JoshLind commented
Thanks @davidiw!

> The problem with this approach is that you assume that the retrieve of a public key should have write abilities on that key, that's dangerous. 

Can you clarify exactly what you mean here? My understanding is that this approach requires: (i) read capabilities (to fetch all the versions); (ii) rotate capabilities; (iii) write capabilities (to set the minimum versions for encryption/decryption and to trim). 
- Are you proposing splitting this up so that trims don't occur automatically on a rotate, but instead we require a separate call trim explicitly? Hence the split in privileges. Or something else?
- Generally, trimming without read capabilities is difficult because you need to be able to provide fault tolerance (e.g., you can try and hold all version numbers in memory so you don't need to read on a trim, but that approach falls apart when the process needs to restart).

2020-10-03 00:50 UTC, davidiw commented on secure/storage/src/vault.rs
sigh, I screwed up...

2020-10-03 00:51 UTC, davidiw commented on secure/storage/src/vault.rs
> +
just hold on to the first key, rotate 5 times, and ensure you cannot get the key.

2020-10-03 00:52 UTC, davidiw approved these changes
let's avoid the code that adds additional "features" if we can

2020-10-05 03:29 UTC, JoshLind commented
Thanks @davidiw! 😄

> just hold on to the first key, rotate 5 times, and ensure you cannot get the key.

I originally thought of that approach but my concern was that it leaves too much "unknown" about the internal state -- e.g., that test will pass if the trimming operation just trims all versions of the key. I know we could get around it by then remembering all versions we fetch and checking they they all exist after rotations etc. but I wanted to be extra neurotic about testing this change because we're doing it so late.. 😟 

I'll land this for now (just to get it in). If you still feel strongly about addressing this, feel free to push back and I'll update the test to be less intrusive.

/land

2020-10-05 04:21 UTC, closed without merging

2020-10-05 16:59 UTC, JoshLind commented on secure/storage/vault/src/lib.rs
> +            .post(&format!("{}/v1/transit/keys/{}/trim", self.host, name));
@mgorven, yeah, I was going to ping you this morning! Seems like you're already on it 😄 Let us know what you need from our side!