Cherry-pick PR #6656 [config] rocksdb options to release 1.0
libra/libra pull request #6710
Opened 2020-11-16 22:39 UTC by lightmark

- Justification and breaking nature (who does it affect? validators, full nodes, tooling, operators, AOS, etc.)
All the node will be affected with the new default rocksdb options.

- Comprehensive test results that demonstrate the fix working and not breaking existing workflows.
Theoretically it doesn't affect libra system behavior but db behaviors. The current cluster tests and dry-run longevity test has proven it is working and not breaking anything.

- Why we must have it for V1 launch.
Because for long run it may trigger OOM.

- What workarounds and alternative we have if we do not push the PR.
provide unlimited memory to each node which seems impractical

2020-11-17 22:59 UTC, dariorussi commented
so is it protecting the OOM the only effect of this PR?
Do we have a sense of when the system OOMs and under which conditions?

2020-11-18 00:43 UTC, sausagee approved these changes

2020-11-18 05:33 UTC, sausagee commented
/land

2020-11-18 05:59 UTC, bors-libra commented
:broken_heart: Test Failed - [commit-workflow](https://circleci.com/workflow-run/fb3c369b-8c6c-4a30-b4cf-d910c32c17ef?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

2020-11-18 07:03 UTC, sausagee commented
/land

2020-11-18 07:53 UTC, bors-libra commented
:broken_heart: Test Failed - [commit-workflow](https://circleci.com/workflow-run/9974c87a-d786-4266-a447-05dab95736e8?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link)

2020-11-18 18:36 UTC, sausagee requested changes

2020-11-18 18:36 UTC, sausagee commented on language/libra-tools/libra-validator-interface/Cargo.toml
> +anyhow = "1.0.34"
@lightmark please revert this version bump.

2020-11-20 00:17 UTC, lightmark commented
@sausagee plz stamp

2020-11-30 16:50 UTC, sausagee approved these changes
/land

2020-11-30 16:56 UTC, bors-libra commented
:broken_heart: Test Failed - [Build images and run cluster test](https://github.com/libra/libra/runs/1475181195)

2020-11-30 18:39 UTC, lightmark commented
@bors-libra land

2020-11-30 19:12 UTC, bors-libra commented
:broken_heart: Test Failed - [Build images and run cluster test](https://github.com/libra/libra/runs/1475859545)

2020-11-30 19:36 UTC, lightmark commented
@bors-libra land

2020-11-30 19:40 UTC, bors-libra commented
:broken_heart: Test Failed - [Build images and run cluster test](https://github.com/libra/libra/runs/1475992255)

2020-12-02 01:25 UTC, sausagee commented
/land

2020-12-02 03:48 UTC, merged